// src/components/Hero.tsx
import type { Component } from 'solid-js'
import Counter from './Counter'

const Hero: Component = () => {
  return (
    <div class="hero min-h-screen" style={{ 'background-image': 'url(https://api.lorem.space/image/shoes?w=1000&h=800)' }}>
      <div class="bg-opacity-45 hero-overlay" />
      <div class="hero-content text-center text-neutral-content">
        <div class="max-w-md">
          <h1 class="mb-5 font-poppins text-5xl font-bold">Hello there</h1>
          <p class="mb-5 font-inter">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
            ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
            ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
            sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
            est laborum.
          </p>
          <button class="btn btn-primary font-poppins">Get Started</button>
          <Counter />
        </div>
      </div>

    </div>
  )
}

export default Hero

// src/components/Hero.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="hero min-h-screen" style="background-image: url(https://api.lorem.space/image/shoes?w=1000&h=800);">
    <div class="hero-overlay bg-opacity-60"></div>
    <div class="hero-content text-center text-neutral-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold font-poppins">Hello there</h1>
        <p class="mb-5 font-inter">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
          exercitationem
          quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
        <button class="btn btn-secondary" type="button" @click="count++">count is: {{ count }}</button>
      </div>
    </div>
  </div>
  <div class="toast toast-end" v-if="count > 5">
    <div class="alert alert-success">
      <div class="font-poppins">
        <span>You've clicked too many times.</span>
      </div>
    </div>
  </div>
</template>
